// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsvkrpniihmreqdybarf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdmtycG5paWhtcmVxZHliYXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDg2OTMsImV4cCI6MjA3MTE4NDY5M30.92w9RFSAgfjTHyWtv0zXV9zwskxXcxMJVjwg9bgx-6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});